version: '3'
networks:
  lamp:
services:
# linux:
#  image: ubuntu:latest
#  restart: always
 mysql:
  depends_on:
   - apache
  image: mysql:5.7
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: cakephptest
   MYSQL_USER: root
   MYSQL_PASSWORD: root
  networks:
    - lamp
 apache:
#  depends_on:
#   - linux
  build: .
  ports:
   - "80:80"
  restart: always
  stdin_open: true
  tty: true
  networks:
    - lamp
